version: '3.9'

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  weather-api:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - BASE_URL=${BASE_URL}
      - SMTP_URL=${SMTP_URL}
    volumes:
      - .:/usr/src/app
    command: sh -c "npm run migrate && npm start"

volumes:
  db_data:
